### ISSUE TITLE
New Maintainer (Redmi K20 Pro)

### ISSUE THREAD

**Issue by OmegaBeam69** [Spark-Rom/official_devices#144]
## Device you want to apply for
Xiaomi 
Your device name and codename
Redmi K20 Pro (Raphael)

## Device tree sources

```
https://github.com/OmegaBeam69/WF_device_xiaomi_raphael/tree/spark-pn
https://github.com/OmegaBeam69/bool-x_xiaomi_raphael
https://github.com/OmegaBeam69/vendor_xiaomi_raphael

## Link to the platform where you have released your unofficial build
```
https://t.me/redmik20proupdates/6641
```

## Other ROM's you maintain officially or unofficially
```
Derpfest & Bliss (Unofficial)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Almost a Year
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/pyro/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

## Contact
### Telegram username
https://t.me/OmegaVerseGroup
Your Telegram username
@OmegaBeam69

**Comment by spkal01** [comment]
Your tree includes many bring up commits for different roms kindly Rebase it to only include bring up for spark

**Comment by whyredfire** [comment]
Where was this updated from? https://github.com/OmegaBeam69/WF_device_xiaomi_raphael/commit/19884b5c26de3b5c9de157402806b779917803cf. 
Stock value: https://dumps.tadiphone.dev/dumps/xiaomi/raphael/-/blob/raphael-user-11-RKQ1.200826.002-V12.5.2.0.RFKMIXM-release-keys/vendor/build.prop#L3

Keep only one of them, https://github.com/OmegaBeam69/WF_device_xiaomi_raphael/blob/e46c1677b3e5a5c83a85fc1c2bb3b41081dd65e0/device.mk#L23-L27. Override Aperture from camera repository instead of overriding from remove packages.

Shipping a third party music player app isn't allowed, https://github.com/OmegaBeam69/WF_device_xiaomi_raphael/commit/fb1a66ae1364fffcffa8a7ca60e20116fffd9eed.

We ship this from source, you can remove it from your device tree https://github.com/OmegaBeam69/WF_device_xiaomi_raphael/commit/62bb28fb734feb6ea1186cc6aa7e688b8a3c6305.

You can drop the following commits too, these are done from Spark vendor itself.
https://github.com/OmegaBeam69/WF_device_xiaomi_raphael/commit/fca44d464761af47b32c87e9ce989ec1b917d555
https://github.com/OmegaBeam69/WF_device_xiaomi_raphael/commit/42c790b236bda08bca8735e8b3ce4780a03a12c2
https://github.com/OmegaBeam69/WF_device_xiaomi_raphael/commit/5383d7137c20838dd691a978fb9dd7370d452270

I recommend you drop this too, we've plenty space for these apps. https://github.com/OmegaBeam69/WF_device_xiaomi_raphael/commit/789d7b12fac9bff23e0169ee1aacc4f4f6255113

We don't have trust hal, https://github.com/OmegaBeam69/WF_device_xiaomi_raphael/commit/a73faf72f5f04c76b701da4ef23724579490badf


Based on the changes mentioned earlier, it seems like you might not have enough experience for this role right now. I recommend that you wait and apply for the official maintainer position when you've gained more experience in the future.
