### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Patriot-06** [Spark-Rom/official_devices#57]
## Device you want to apply for
```
Realme X3 Series (x3)
```

## Device tree sources

```
https://github.com/Patriot-06/android_device_realme_x3
https://github.com/Patriot-06/android_kernel_realme_x3
https://github.com/Patriot-06/android_vendor_realme_x3
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
PPUI (Officially)
Project Elixir (Officially)
crDroid Android (Officially)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Years
```

## Did you properly read [Device stability requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/requirements.md) and [Maintainer requirements](https://github.com/Spark-Rom/official_devices/blob/eleven/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Permissive for now.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
https://t.me/patriot_235
```

**Comment by spkal01** [comment]
Hey thanks for applying but im afraid there are some issues with your form.
1 you havent inserted a link to your unofficial build
2 your trees arent adapted to spark
3 You havent inserted a valid amount of since when you are building 
4 We only accept people who build 3 roms including spark

Reopen this issue once you have adressed all of the above issues
